---

# Required as Ubuntu ships with Python3 and not 2
ansible_python_interpreter: /usr/bin/python3

# System's timezone
configure_timezone: 'Europe/Madrid'

# Additional user to create
configure_user_name: 'hector'
configure_user_password: 'hector'

# List of apt-keys to load from disk
# See "extra_packages" role.
extra_packages_keys: []

# List of apt-keys to load from URLs.
# See "extra_packages" role
extra_packages_keys_url:
  - url: 'https://dl.google.com/linux/linux_signing_key.pub'
  - url: 'https://download.sublimetext.com/sublimehq-pub.gpg'

# Extra apt repositories to add
# See "extra_packages" role
extra_packages_repositories:
  - name: 'google-chrome'
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
  - name: 'sublime_text'
    repo: 'deb https://download.sublimetext.com/ apt/stable/'

# Extra APT packages to install
# See "extra_packages" role
extra_packages_list:
  # Everyday apps
  - 'thunderbird'
  - 'gnome-calendar'
  - 'firefox'
  - 'google-chrome-stable'
  - 'keepassxc'
  - 'libreoffice'
  - 'mythes-gl'
  - 'hyphen-gl'
  - 'calibre'

  # Gaming
  - 'steam'

  # Programming
  - 'sublime-text'
  - 'clang-format'
  - 'composer'
  - 'cppcheck'
  - 'fonts-firacode'
  - 'git'
  - 'lua-check'
  - 'luarocks'
  - 'nodejs'
  - 'npm'
  - 'php-cli'
  - 'php-mbstring'
  - 'php-xml'
  - 'phpunit'
  - 'python3'
  - 'pylint'
  - 'python3-pip'
  - 'shellcheck'
  - 'sqlite3'
  - 'vagrant'
  - 'virtualbox'

  # CLI
  - 'terminator'
  - 'iotop'
  - 'mysql-client'
  - 'strace'
  - 'telnet'
  - 'unrar'
  - 'unzip'
  - 'vim'
  - 'nmap'

  # Media
  - 'vlc'
  - 'gimp'

  # System utils
  - 'gpg'
  - 'gparted'
  - 'p7zip'
  - 'p7zip-full'
  - 'default-jdk'
  # - 'gnome-shell-extension-dashtodock'

# Snap packages to install
extra_packages_snaps:
  - name: 'discord'
  - name: 'spotify'
  - name: 'bitwarden'
  - name: 'phpstorm'
    classic: true

# Pip packages to install
extra_packages_pip:
  - name: 'ansible'
    executable: pip3
  - name: 'ansible-lint'
    executable: pip3
  - name: 'molecule'
    executable: pip3
  - name: 'yamllint'
    executable: pip3
  - name: 'docker'
    executable: pip3

# NPM utils
extra_packages_npm:
  - name: 'jshint'
    global: true

docker_apt_release_channel: 'stable'

# Docker users
docker_users: ["{{ configure_user_name}}"]

# Git configuration for the .gitconfig file
git_config:
  user:
    name: 'HÃ©ctor Luaces'
    email: "{{ vault_email }}"
    signingkey: 'F634A48B203E73CA'
  core:
    editor: 'vi'
    excludesfile: '~/.gitignore'
    fileMode: 'false'
  web:
    browser: 'google-chrome'
  color:
    diff: 'auto'
    status: 'auto'
    branch: 'auto'
    interactive: 'auto'
    ui: 'true'
    pager: 'true'
  commit:
    gpgsign: 'true'

# Configuration files for the newly created user
configuration_files_user:
  # Thunderbird configuration. It is not fuly portable but it makes things
  # waaaaay easier.
  - type: 'file'
    dest: '~/.thunderbird/'
    src: 'thunderbird/profiles.ini'
  - type: 'file'
    dest: '~/.thunderbird/'
    src: 'thunderbird/installs.ini'
  - type: 'file'
    dest: "~/.thunderbird/{{ configure_user_name }}.default"
    src: 'thunderbird/prefs.js'

  # Terminator
  - type: 'file'
    dest: '~/.config/terminator/'
    src: 'terminator/config'

  # Private keys
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/config'
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/red-queen'
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/red-queen.pub'
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/chesire'
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/chesire.pub'
  - type: 'file'
    dest: '~/.ssh/'
    dest_mode: '700'
    mode: '600'
    src: 'ssh/git'
  # Sublime text configuration. Too much stuff in here to not do this...
  - type: 'repo'
    accept_hostkey: true
    repo: "{{ vault_sublime_text_repo }}"
    version: 'master'
    key_file: "~/.ssh/git"
    dest: "~/.config/sublime-text-3"
    force: true

# Various Gnome settings to be configured using the gsettings tool
gnome_settings:
  # Dark theme
  - key: '/org/gnome/desktop/interface/gtk-theme'
    value: "'Yaru-dark'"

  # Night light
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    value: 'true'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-temperature'
    value: 'uint32 3140'
  - key: '/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic'
    value: 'true'

  # Screenshots
  - key: '/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip'
    value: '["<Primary><Shift><Alt>dollar"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/window-screenshot'
    value: '["<Alt>Print"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/area-screenshot'
    value: '["<Shift><Alt>dollar"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip'
    value: '["<Alt>3"]'
  - key: '/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip'
    value: '["<Shift><Alt>periodcentered"]'

  # Custom keybindings
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
    value: '["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/"]'

  # Custom keybinding #0: tilix quake dropdown
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding'
    value: "'masculine'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command'
    value: "'tilix --quake'"
  - key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name'
    value: "'tilix --quake'"

  # Emoji selector (conflicts with a keybinding for terminator)
  - key: '/org/freedesktop/ibus/panel/emoji/hotkey'
    value: '["<Control><Shift>space"]'

  # Calendar configuration
  - key: '/org/gnome/desktop/calendar/show-weekdate'
    value: 'true'
  - key: '/org/gnome/desktop/interface/clock-show-date'
    value: 'true'

  # Privacy
  - key: '/org/gnome/desktop/privacy/send-software-usage-stats'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/report-technical-problems'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remember-app-usage'
    value: 'false'
  - key: '/org/gnome/desktop/privacy/remove-old-temp-files'
    value: 'true'
  - key: '/org/gnome/desktop/privacy/remember-recent-files'
    value: 'false'
