---

- name: 'Disable apt-daily services to unlock dpkg'
  systemd:
    name: '{{ item }}'
    state: 'stopped'
    enabled: false
  loop: "{{ apt_lock_holders }}"
  notify: ['enable apt_lock_holders']

- name: 'Stop apt-daily-upgrade.timer'
  systemd:
    name: 'apt-daily-upgrade.timer'
    state: 'stopped'
    enabled: 'no'

- name: 'Update Ubuntu Drivers'
  command: 'ubuntu-drivers autoinstall'
  when: ansible_virtualization_role != 'guest'
  ignore_errors: true

- name: 'Install base packages'
  apt:
    name: "{{ item }}"
    state: 'present'
  loop:
    # So that ansible does not complain. See issue #56832 @ ansible
    - aptitude
    - ubuntu-restricted-extras
    - gnome-tweak-tool
    - apt-transport-https

- name: "Refresh apt-cache (apt-get update)"
  apt:
    update_cache: true
