---
# vars file for role_template

# Services or units that can block the dkpg lockfile causing ansible to fail
apt_lock_holders:
  - "apt-daily-upgrade.service"
  - "apt-daily-upgrade.timer"
  - "apt-daily.timer"
  - "apt-daily.service"
  - "unattended-upgrades.service"
