---

- name: 'enable apt_lock_holders'
  systemd:
    name: '{{ item }}'
    state: 'started'
    enabled: true
  loop: "{{ apt_lock_holders }}"
  # I really, really, really do not like this, but apparently the current
  # systemd module fails when dealing with masked units, so I'm going to
  # leave this here until a new ansible releases fixes this ğŸ™
  ignore_errors: true
