---

- name: 'Build local vendor role repository'
  hosts: localhost
  connection: local
  vars:
    force_purge: false
    installation_dir: roles/vendors
    installation_prefix: ../

  tasks:
    - name: Remove existing vendor roles
      file:
        path: "{{ installation_prefix }}{{ installation_dir }}"
        state: absent
      when: force_purge | bool

    - name: Install all vendor roles
      command: >
        ansible-galaxy install
        {{ ( force_purge | bool ) | ternary('--force','') }}
        --role-file {{ installation_prefix }}roles/requirements.yml
        --roles-path {{ installation_prefix }}{{ installation_dir }}

