---
galaxy_info:
  author: HÃ©ctor Luaces <hector@luaces-novo.es>
  role_name: ulauncher
  namespace: hluaces
  description: Installs ULauncher
  license: MIT
  min_ansible_version: '2.8'

  platforms:
    - name: 'Ubuntu'
      versions: ['focal']
  galaxy_tags: []
dependencies: []
