---
name: Clean up offline runners
on:
  schedule:
    - cron: "30 07 * * *"
  workflow_dispatch:

jobs:
  scaleway:
    name: Clean up self-hosted runners
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Clean up GitHub runners
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_RUNNERS }}
        uses: ./.github/actions/runners/delete_offline
        with:
          repository: ${{ github.repository }}
